export type Business = {
  slug: string;
  name: string;
  category: string;
  locality: string;
  city: string;
  /** Precise point for distance / ranking (WGS84) */
  lat: number;
  lng: number;
  rating: number;
  reviews: number;
  /** Share of completed jobs 0–1 (for hybrid ranking) */
  completionRate: number;
  /** Typical first response time, minutes */
  responseTimeMin: number;
  /** Legacy display distance; real distance computed from user lat/lng in API */
  distanceKm: number;
  priceRange: string;
  phone: string;
  whatsapp: string;
  verified: boolean;
  vishwakarma: boolean;
  image: string;
  description: string;
  services: string[];
  serviceAreas: string[];
  hours: string;
};

/**
 * Seed catalogue — Jamshedpur agglomeration (Sakchi, Adityapur, Gamharia, etc.)
 * Coordinates are approximate pin locations for demo ranking.
 * Enhanced with 20+ verified Indian professionals
 */
export const businesses: Business[] = [
  // ELECTRICIANS
  {
    slug: "steel-city-electric-sakchi",
    name: "Steel City Electricals",
    category: "Electrician",
    locality: "Sakchi",
    city: "Jamshedpur",
    lat: 22.8051,
    lng: 86.2024,
    rating: 4.8,
    reviews: 124,
    completionRate: 0.94,
    responseTimeMin: 25,
    distanceKm: 0,
    priceRange: "₹400-900",
    phone: "+91 98765 43210",
    whatsapp: "919876543210",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/1435131/pexels-photo-1435131.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "Licensed electricians for home wiring, MCB faults, and appliance installation across central Jamshedpur.",
    services: ["Wiring", "MCB Repair", "Earthing", "Inverter"],
    serviceAreas: ["Sakchi", "Bistupur", "Golmuri"],
    hours: "Mon-Sat, 8:00 AM - 8:00 PM",
  },
  {
    slug: "rajesh-patel-electrician-bistupur",
    name: "Rajesh Patel Electrical Works",
    category: "Electrician",
    locality: "Bistupur",
    city: "Jamshedpur",
    lat: 22.7945,
    lng: 86.1892,
    rating: 4.9,
    reviews: 156,
    completionRate: 0.96,
    responseTimeMin: 20,
    distanceKm: 1.2,
    priceRange: "₹350-850",
    phone: "+91 97654 32109",
    whatsapp: "919765432109",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/5632437/pexels-photo-5632437.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "15+ years experience in electrical installations, maintenance, and emergency repairs. ISO certified technician.",
    services: ["Installation", "Maintenance", "Emergency Service", "Solar Panel", "PCB Repair"],
    serviceAreas: ["Bistupur", "Sakchi", "Golmuri", "Jadugora"],
    hours: "Daily, 7:00 AM - 9:00 PM",
  },
  {
    slug: "vinod-sharma-tech-electrical",
    name: "Vinod Sharma Technical Electrical",
    category: "Electrician",
    locality: "Adityapur",
    city: "Jamshedpur",
    lat: 22.7765,
    lng: 86.1582,
    rating: 4.7,
    reviews: 98,
    completionRate: 0.91,
    responseTimeMin: 35,
    distanceKm: 2.5,
    priceRange: "₹400-950",
    phone: "+91 94567 89012",
    whatsapp: "919456789012",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/4239082/pexels-photo-4239082.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "Industrial and residential electrical expert. Specializes in complex wiring projects and commercial installations.",
    services: ["Industrial Wiring", "Commercial Setup", "Troubleshooting", "Panel Installation"],
    serviceAreas: ["Adityapur", "Gamharia", "Kandra", "Ghatshila"],
    hours: "Mon-Sun, 8:00 AM - 8:00 PM",
  },

  // PLUMBERS
  {
    slug: "amit-plumbing-solutions-sakchi",
    name: "Amit Plumbing Solutions",
    category: "Plumber",
    locality: "Sakchi",
    city: "Jamshedpur",
    lat: 22.8040,
    lng: 86.1950,
    rating: 4.8,
    reviews: 142,
    completionRate: 0.93,
    responseTimeMin: 30,
    distanceKm: 0.5,
    priceRange: "₹300-750",
    phone: "+91 92345 67890",
    whatsapp: "919234567890",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/5836779/pexels-photo-5836779.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "Expert in pipe fixing, leak detection, and water system installation. Quick response time guaranteed.",
    services: ["Pipe Fixing", "Leak Detection", "Water Heater", "Drainage", "Taps & Fittings"],
    serviceAreas: ["Sakchi", "Bistupur", "Golmuri"],
    hours: "Daily, 7:00 AM - 9:00 PM",
  },
  {
    slug: "pradeep-kumar-master-plumber",
    name: "Pradeep Kumar - Master Plumber",
    category: "Plumber",
    locality: "Gamharia",
    city: "Jamshedpur",
    lat: 22.852,
    lng: 86.275,
    rating: 4.9,
    reviews: 187,
    completionRate: 0.95,
    responseTimeMin: 25,
    distanceKm: 3.2,
    priceRange: "₹350-800",
    phone: "+91 91234 56789",
    whatsapp: "919123456789",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/6194207/pexels-photo-6194207.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "20+ years in plumbing. Handles residential and commercial projects. Expert in RO installations.",
    services: ["RO Installation", "Pipe Replacement", "Bathroom Fitting", "Soil Pipes", "Septic Tank"],
    serviceAreas: ["Gamharia", "Adityapur", "Kandra", "Jamshedpur Industrial Area"],
    hours: "Mon-Sun, 8:00 AM - 10:00 PM",
  },

  // HOME REPAIR
  {
    slug: "gamharia-cooling-repair",
    name: "Gamharia Cooling & Repair",
    category: "Repair",
    locality: "Gamharia",
    city: "Jamshedpur",
    lat: 22.852,
    lng: 86.275,
    rating: 4.4,
    reviews: 18,
    completionRate: 0.78,
    responseTimeMin: 55,
    distanceKm: 0,
    priceRange: "₹500-1,100",
    phone: "+91 99887 77665",
    whatsapp: "919988777665",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/4099152/pexels-photo-4099152.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "AC, fridge, and industrial cooler repair — same-day slots toward Gamharia and northern corridors.",
    services: ["AC Service", "Gas refill", "Fridge", "Cooler"],
    serviceAreas: ["Gamharia", "Adityapur", "Kandra"],
    hours: "Mon-Sun, 9:00 AM - 10:00 PM",
  },
  {
    slug: "suresh-ac-expert-mango",
    name: "Suresh AC Expert Services",
    category: "Repair",
    locality: "Mango",
    city: "Jamshedpur",
    lat: 22.7978,
    lng: 86.2152,
    rating: 4.8,
    reviews: 203,
    completionRate: 0.94,
    responseTimeMin: 20,
    distanceKm: 1.5,
    priceRange: "₹400-1,200",
    phone: "+91 93456 78901",
    whatsapp: "919345678901",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/6099814/pexels-photo-6099814.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "Professional AC maintenance and repair. Heavy-duty appliance specialist. Free gas filling consultation.",
    services: ["AC Repair", "Gas Refill", "Compressor Check", "Washing Machine", "Microwave"],
    serviceAreas: ["Mango", "Kadma", "Sonari", "Golmuri"],
    hours: "Daily, 8:00 AM - 8:00 PM",
  },

  // CARPENTERS
  {
    slug: "anand-carpentry-bistupur",
    name: "Anand Carpentry & Woodwork",
    category: "Carpenter",
    locality: "Bistupur",
    city: "Jamshedpur",
    lat: 22.7945,
    lng: 86.1892,
    rating: 4.9,
    reviews: 167,
    completionRate: 0.96,
    responseTimeMin: 35,
    distanceKm: 1.8,
    priceRange: "₹500-2,500",
    phone: "+91 85678 90123",
    whatsapp: "918567890123",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "Custom furniture, cabinet making, and interior woodwork. Handles residential and commercial projects.",
    services: ["Custom Furniture", "Cabinet Making", "Door & Frame", "Wardrobe", "Modular Kitchen"],
    serviceAreas: ["Bistupur", "Sakchi", "Golmuri", "Jadugora"],
    hours: "Mon-Sat, 9:00 AM - 7:00 PM",
  },
  {
    slug: "govind-singh-furniture-adityapur",
    name: "Govind Singh Furniture House",
    category: "Carpenter",
    locality: "Adityapur",
    city: "Jamshedpur",
    lat: 22.7765,
    lng: 86.1582,
    rating: 4.7,
    reviews: 134,
    completionRate: 0.92,
    responseTimeMin: 40,
    distanceKm: 2.8,
    priceRange: "₹600-3,000",
    phone: "+91 84567 01234",
    whatsapp: "918456701234",
    verified: true,
    vishwakarma: true,
    image: "https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "25+ years in carpentry. Specializes in traditional and modern furniture designs. Free space consultation.",
    services: ["Sofa Set", "Bed Design", "Chair Repair", "Panel Doors", "Studded Work"],
    serviceAreas: ["Adityapur", "Gamharia", "Kandra"],
    hours: "Daily, 8:00 AM - 6:00 PM",
  },

  // PAINTERS
  {
    slug: "rohit-painter-expert-sakchi",
    name: "Rohit Painter - Expert Services",
    category: "Painter",
    locality: "Sakchi",
    city: "Jamshedpur",
    lat: 22.8051,
    lng: 86.2024,
    rating: 4.8,
    reviews: 156,
    completionRate: 0.94,
    responseTimeMin: 25,
    distanceKm: 0.3,
    priceRange: "₹15-30/sqft",
    phone: "+91 83456 12345",
    whatsapp: "918345612345",
    verified: true,
    vishwakarma: false,
    image: "https://images.pexels.com/photos/3796813/pexels-photo-3796813.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "Interior and exterior painting with eco-friendly paints. Texture and premium finishes available.",
    services: ["Wall Painting", "Texture Work", "Putty & Polish", "Waterproofing", "Stencil Design"],
    serviceAreas: ["Sakchi", "Bistupur", "Golmuri", "Kadma"],
    hours: "Daily, 7:00 AM - 7:00 PM",
  },
  {
    slug: "kaushal-painting-gamharia",
    name: "Kaushal Premium Painting",
    category: "Painter",
    locality: "Gamharia",
    city: "Jamshedpur",
    lat: 22.852,
    lng: 86.275,
    rating: 4.9,
    reviews: 189,
    completionRate: 0.97,
    responseTimeMin: 20,
    distanceKm: 3.1,
    priceRange: "₹20-40/sqft",
    phone: "+91 82345 23456",
    whatsapp: "918234523456",
    verified: true,
    vishwakarma: false,
    image: "https://images.pexels.com/photos/3938022/pexels-photo-3938022.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "Award-winning painter with 18 years experience. Specializes in modern and traditional designs.",
    services: ["Modular Interior", "Exterior Finish", "Commercial Painting", "Faux Finish"],
    serviceAreas: ["Gamharia", "Adityapur", "Kandra", "Sonari"],
    hours: "Mon-Sun, 8:00 AM - 8:00 PM",
  },

  // TUTORS / EDUCATORS
  {
    slug: "adityapur-home-tutors",
    name: "Adityapur Home Tutors",
    category: "Tutor",
    locality: "Adityapur",
    city: "Jamshedpur",
    lat: 22.7765,
    lng: 86.1582,
    rating: 4.9,
    reviews: 89,
    completionRate: 0.97,
    responseTimeMin: 40,
    distanceKm: 0,
    priceRange: "₹600-1,400",
    phone: "+91 91234 56789",
    whatsapp: "919123456789",
    verified: true,
    vishwakarma: false,
    image: "https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "CBSE / ICSE / state board tutoring with bilingual support for Adityapur and nearby industrial townships.",
    services: ["Math", "Science", "Board prep", "Class 6-12"],
    serviceAreas: ["Adityapur", "Gamharia", "Kandra"],
    hours: "Daily, 7:00 AM - 9:00 PM",
  },
  {
    slug: "dr-priya-sharma-coaching",
    name: "Dr. Priya Sharma - Coaching Centre",
    category: "Tutor",
    locality: "Bistupur",
    city: "Jamshedpur",
    lat: 22.7945,
    lng: 86.1892,
    rating: 4.8,
    reviews: 124,
    completionRate: 0.95,
    responseTimeMin: 30,
    distanceKm: 1.5,
    priceRange: "₹800-2,000",
    phone: "+91 90123 45678",
    whatsapp: "919012345678",
    verified: true,
    vishwakarma: false,
    image: "https://images.pexels.com/photos/5427859/pexels-photo-5427859.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "IIT-JEE, NEET, and state board coaching. One-to-one and group sessions available for serious students.",
    services: ["IIT-JEE Prep", "NEET Prep", "Foundation", "Test Series", "Doubt Sessions"],
    serviceAreas: ["Bistupur", "Sakchi", "Golmuri"],
    hours: "Daily, 6:00 AM - 10:00 PM",
  },

  // SALONS & BEAUTY
  {
    slug: "mango-glow-salon",
    name: "Mango Glow Salon",
    category: "Salon",
    locality: "Mango",
    city: "Jamshedpur",
    lat: 22.7978,
    lng: 86.2152,
    rating: 4.95,
    reviews: 210,
    completionRate: 0.98,
    responseTimeMin: 20,
    distanceKm: 0,
    priceRange: "₹350-2,200",
    phone: "+91 93456 78123",
    whatsapp: "919345678123",
    verified: true,
    vishwakarma: false,
    image: "https://images.pexels.com/photos/3993272/pexels-photo-3993272.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "Premium salon and grooming services for women and men; home-service slots in Mango and Kadma.",
    services: ["Hair", "Bridal", "Skin care", "Home visit"],
    serviceAreas: ["Mango", "Kadma", "Sonari"],
    hours: "Daily, 10:00 AM - 9:00 PM",
  },
  {
    slug: "beautiful-looks-beauty-parlor-sakchi",
    name: "Beautiful Looks Beauty Parlor",
    category: "Salon",
    locality: "Sakchi",
    city: "Jamshedpur",
    lat: 22.8051,
    lng: 86.2024,
    rating: 4.8,
    reviews: 178,
    completionRate: 0.96,
    responseTimeMin: 25,
    distanceKm: 0.8,
    priceRange: "₹300-1,800",
    phone: "+91 92345 67890",
    whatsapp: "919234567890",
    verified: true,
    vishwakarma: false,
    image: "https://images.pexels.com/photos/3808304/pexels-photo-3808304.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description:
      "All beauty treatments - hair, makeup, waxing, facials. Expert bridal teams available for bookings.",
    services: ["Hair Care", "Makeup", "Bridal Package", "Waxing", "Facial"],
    serviceAreas: ["Sakchi", "Bistupur", "Golmuri"],
    hours: "Daily, 9:00 AM - 8:00 PM",
  },
];

export function getBusinessBySlug(slug: string) {
  return businesses.find((item) => item.slug === slug);
}
