// Practical Questions Database for Skill Tests
import type { PracticalQuestion, SkillTest } from "./types/skills";

// PLUMBING SKILL TEST - 10 Practical Questions
export const plumbingQuestions: PracticalQuestion[] = [
  {
    id: "plumbing-1",
    question:
      "A customer reports water continuously dripping from a tap despite turning it off. What is the most likely issue?",
    scenario:
      "You arrive at a customer's home. The kitchen tap is dripping at a rate of 1 drop every 3 seconds even when fully turned off.",
    options: {
      a: "The water pressure is too high in the mains",
      b: "The tap washer is worn out and needs replacement",
      c: "The pipes are frozen",
      d: "The water heater is malfunctioning",
    },
    correctAnswer: "b",
    explanation:
      "A dripping tap with the handle fully turned off indicates a worn out washer or seal inside the tap. This is the most common issue and easiest to fix.",
    skillRequired: "plumbing",
    difficulty: "easy",
  },
  {
    id: "plumbing-2",
    question:
      "Water is backing up in the bathroom sink. It drains slowly when someone applies pressure. What's your diagnostic approach?",
    scenario:
      "Customer's bathroom sink is clogged. Manual plunging helps momentarily, but water backs up quickly again.",
    options: {
      a: "Use a chemical drain cleaner immediately",
      b: "Check for blockage using a plumbing snake; identify if it's in the P-trap or further down",
      c: "Replace the entire drain pipe",
      d: "Install a new sink",
    },
    correctAnswer: "b",
    explanation:
      "Always diagnose the blockage location first. A plumbing snake helps identify if the blockage is in the accessible P-trap or requires further investigation.",
    skillRequired: "plumbing",
    difficulty: "medium",
  },
  {
    id: "plumbing-3",
    question:
      "There's a leak in the copper pipe joint under the sink. How should you approach the repair?",
    scenario:
      "Water is actively dripping from a soldered joint between two copper pipes. The customer needs the leak fixed today.",
    options: {
      a: "Wrap it with duct tape as a temporary fix",
      b: "Drain the system, desolder the joint, clean both pipes, and re-solder with proper flux and solder",
      c: "Apply plumber's putty to seal the leak",
      d: "Tighten the connection with a wrench",
    },
    correctAnswer: "b",
    explanation:
      "Proper repair of leaking soldered joints requires draining the system, removing the old solder, cleaning the pipes thoroughly, and creating a new tight solder joint.",
    skillRequired: "plumbing",
    difficulty: "hard",
  },
  {
    id: "plumbing-4",
    question:
      "A customer complains of low water pressure throughout their house. How do you troubleshoot?",
    scenario:
      "Water pressure is weak at all fixtures - taps, shower, and toilet. The customer thinks something is wrong with the main supply.",
    options: {
      a: "Immediately blame the municipal water supply",
      b: "Check the main water shutoff valve and water meter; look for leaks in visible pipes",
      c: "Install a pump booster first",
      d: "Replace all the pipes in the house",
    },
    correctAnswer: "b",
    explanation:
      "Start by checking if the main shutoff valve is partially closed or if there are visible leaks. These are common causes of low pressure that are easy to identify and fix.",
    skillRequired: "plumbing",
    difficulty: "medium",
  },
  {
    id: "plumbing-5",
    question: "How should you safely shut off a burst water pipe in an emergency?",
    scenario:
      "A customer calls - they have a burst pipe spraying water in their basement. They're panicked. What do you tell them to do first?",
    options: {
      a: "Leave it and wait for you to arrive",
      b: "Locate and close the main water shutoff valve immediately; if they can't find it, have them turn off individual fixture shutoff valves",
      c: "Try to tape the burst section",
      d: "Open all the taps to reduce pressure",
    },
    correctAnswer: "b",
    explanation:
      "The primary action in a burst pipe emergency is to shut off the water supply at the main shutoff valve. This stops water wastage and damage before repair.",
    skillRequired: "plumbing",
    difficulty: "easy",
  },
  {
    id: "plumbing-6",
    question:
      "You're installing a new toilet and need to ensure proper water seal in the trap. What's critical?",
    scenario:
      "Installing a new toilet. You need to ensure the bowl has proper water seal to prevent sewer gases from entering.",
    options: {
      a: "Skip the water seal and use deodorant instead",
      b: "Ensure at least 1-2 inches of water remains in the trap after flushing",
      c: "Fill the bowl with excess water",
      d: "Use a drain stopper",
    },
    correctAnswer: "b",
    explanation:
      "A proper water seal of 1-2 inches in the trap is essential to prevent sewer gases and odors from backing into the house. This is a fundamental principle of toilet installation.",
    skillRequired: "plumbing",
    difficulty: "medium",
  },
  {
    id: "plumbing-7",
    question: "A customer reports hot water is not reaching their tap. What's your investigation?",
    scenario:
      "The cold water tap works fine, but no hot water comes out when they open the hot water tap.",
    options: {
      a: "Replace the water heater",
      b: "Check if the water heater is functioning, the supply line isn't kinked, and the hot water valve at the fixture isn't stuck",
      c: "Assume the heater is broken",
      d: "Drain all hot water tanks",
    },
    correctAnswer: "b",
    explanation:
      "Before assuming heater failure, verify the heater is on, check for kinked supply lines, and ensure the isolated valve at the fixture is fully open.",
    skillRequired: "plumbing",
    difficulty: "medium",
  },
  {
    id: "plumbing-8",
    question: "How do you prevent water hammer (loud banging noise) in pipes?",
    scenario:
      "After a tap is turned off quickly, there's a loud banging sound in the pipes. The customer finds it alarming.",
    options: {
      a: "Ignore it - it's normal",
      b: "Install water hammer arresters or slow-close valves to absorb pressure shock",
      c: "Increase water pressure",
      d: "Add more pipes",
    },
    correctAnswer: "b",
    explanation:
      "Water hammer is caused by sudden pressure changes. Installing arresters or slow-closing valves absorbs this shock and prevents damage to pipes.",
    skillRequired: "plumbing",
    difficulty: "hard",
  },
  {
    id: "plumbing-9",
    question:
      "When replacing a faucet washer, what safety precaution is most important?",
    scenario:
      "Customer wants you to fix their dripping tap by replacing the washer.",
    options: {
      a: "Work on it without shutting off water",
      b: "Shut off the water supply to that fixture or the main valve before disassembling",
      c: "Use boiling water to loosen connections",
      d: "Work quickly to minimize water exposure",
    },
    correctAnswer: "b",
    explanation:
      "Always shut off the water supply before disassembling any plumbing fixture to prevent water spray and flooding.",
    skillRequired: "plumbing",
    difficulty: "easy",
  },
  {
    id: "plumbing-10",
    question: "A toilet keeps running after flushing. What's the most common cause?",
    scenario:
      "The customer reports water constantly trickling into the toilet bowl after flushing. The fill valve refills frequently.",
    options: {
      a: "The tank is too small",
      b: "The flapper valve is leaking or the fill valve is faulty; check by adding food coloring to the tank",
      c: "The bowl design is wrong",
      d: "Water pressure is too high",
    },
    correctAnswer: "b",
    explanation:
      "A constantly running toilet usually means water is leaking from the tank through a faulty flapper or the fill valve isn't shutting off properly. Food coloring helps diagnose which component is leaking.",
    skillRequired: "plumbing",
    difficulty: "medium",
  },
];

// ELECTRICAL SKILL TEST - 10 Practical Questions
export const electricalQuestions: PracticalQuestion[] = [
  {
    id: "elec-1",
    question: "A client reports that multiple sockets in a room have stopped working simultaneously. What do you check first?",
    scenario: "In a typical residential setup, you find 3 wall outlets in the guest room are dead. Lights in the same room are still working.",
    options: {
      a: "The main energy meter for the house",
      b: "The circuit breaker (MCB) in the distribution board for that specific sub-circuit",
      c: "Each socket one-by-one with a continuity tester",
      d: "The light switch in the room",
    },
    correctAnswer: "b",
    explanation: "If multiple sockets stop at once while lights remain on, it's almost always a tripped circuit breaker specific to that socket ring or radial circuit.",
    skillRequired: "electrical",
    difficulty: "easy",
  },
  {
    id: "elec-2",
    question: "Which instrument is most reliable for identifying a 'live' wire without making physical contact?",
    scenario: "You need to identify whether a wire inside a switch box is energized before starting any work.",
    options: {
      a: "A regular screwdriver with a neon bulb",
      b: "A non-contact voltage tester (NCV)",
      c: "A digital multimeter with probes",
      d: "A clamp meter",
    },
    correctAnswer: "b",
    explanation: "Non-contact voltage testers allow for quick identification of energized conductors through the insulation, increasing safety.",
    skillRequired: "electrical",
    difficulty: "easy",
  },
  {
    id: "elec-3",
    question: "A ceiling fan is humming loudly but not spinning or spinning very slowly. What is the most likely faulty component?",
    scenario: "You're troubleshooting a fan. It makes a distinct low-frequency hum when switched on, but requires a manual push to start rotating.",
    options: {
      a: "The speed regulator",
      b: "The run/start capacitor",
      c: "The main magnetic bearings",
      d: "The copper winding in the stator",
    },
    correctAnswer: "b",
    explanation: "A humming fan that won't start by itself usually has a failed capacitor which provides the necessary phase shift for starting torque.",
    skillRequired: "electrical",
    difficulty: "medium",
  },
  {
    id: "elec-4",
    question: "What is the standard color coding for the Earth (Ground) wire in modern Indian household wiring?",
    scenario: "You are wiring a new 3-pin plug for a washing machine.",
    options: {
      a: "Red or Brown",
      b: "Black or Blue",
      c: "Green or Green-Yellow",
      d: "White or Grey",
    },
    correctAnswer: "c",
    explanation: "Green or dual-toned Green-Yellow is the international and Indian standard for grounding/earth connections.",
    skillRequired: "electrical",
    difficulty: "easy",
  },
  {
    id: "elec-5",
    question: "A customer experiences a mild shock when touching the metal body of a refrigerator. What does this indicate?",
    scenario: "A client claims 'current lagta hai' when opening the fridge door with wet hands.",
    options: {
      a: "The refrigerator is working fine; this is normal static",
      b: "There is a leakage or short-to-ground, and the appliance/socket is not properly earthed",
      c: "The water level in the motor is too high",
      d: "The compressor is overheating",
    },
    correctAnswer: "b",
    explanation: "A shock from a metal surface indicates that the chassis has become live due to a fault, and the lack of a proper earthing system is failing to redirect that current to the ground.",
    skillRequired: "electrical",
    difficulty: "medium",
  },
  {
    id: "elec-6",
    question: "Before performing any maintenance on a main distribution panel, what is the 'Golden Rule' of electrical safety?",
    scenario: "You are tasked to replace a faulty RCD/ELCB in a Main Panel.",
    options: {
      a: "Wear rubber gloves",
      b: "Isolate, lock-out, and tag-out (LOTO) the power supply and verify zero voltage with a meter",
      c: "Use only one hand while working",
      d: "Work as fast as possible to prevent heat buildup",
    },
    correctAnswer: "b",
    explanation: "LOTO procedures ensure the circuit cannot be accidentally energized while you are working on it, which is the most critical safety protocol.",
    skillRequired: "electrical",
    difficulty: "hard",
  },
  {
    id: "elec-7",
    question: "When selecting a cable for a 1.5 Ton split Air Conditioner, which factor is most important for long-term safety?",
    scenario: "You are drawing a new power line from the DB to the AC outdoor unit.",
    options: {
      a: "The color of the insulation",
      b: "The flexibility of the wire",
      c: "The current-carrying capacity (Ampacity) and cross-sectional area (sq mm)",
      d: "The length should be as short as possible",
    },
    correctAnswer: "c",
    explanation: "AC units draw significant current; using an undersized cable leads to overheating, insulation failure, and potential fires.",
    skillRequired: "electrical",
    difficulty: "medium",
  },
  {
    id: "elec-8",
    question: "What is the purpose of an MCB (Miniature Circuit Breaker)?",
    scenario: "A customer asks why they should replace their old ceramic fuse with an MCB.",
    options: {
      a: "To regulate the voltage to appliances",
      b: "To protect against overloading and short-circuit faults",
      c: "To save electricity costs",
      d: "To act as a light switch",
    },
    correctAnswer: "b",
    explanation: "MCBs protect circuits from damage by cutting off the power automatically when current exceeds safe levels (overload) or when a short circuit occurs.",
    skillRequired: "electrical",
    difficulty: "easy",
  },
  {
    id: "elec-9",
    question: "A customer's lights flicker when a heavy appliance like a motor or geyser turns on. What is the most likely cause?",
    scenario: "Every time the water pump starts, the LED bulbs in the living room dim significantly for a second.",
    options: {
      a: "The bulbs are reaching the end of their life",
      b: "Voltage drop due to high starting current or loose connections in the service line",
      c: "The water pump is failing",
      d: "The earthing wire is too thin",
    },
    correctAnswer: "b",
    explanation: "Heavy inductive loads draw high starting current, causing a temporary voltage drop across the system if the wiring capacity is borderline or connections are loose.",
    skillRequired: "electrical",
    difficulty: "hard",
  },
  {
    id: "elec-10",
    question: "Why should you never use water to extinguish an electrical fire?",
    scenario: "A switchboard starts sparking and catches fire with visible smoke.",
    options: {
      a: "It will cool the fire too fast",
      b: "It can cause steam burns",
      c: "Water is conductive and can electrocute the person fighting the fire; it also spreads the short circuit",
      d: "It will make the room too messy",
    },
    correctAnswer: "c",
    explanation: "Water conducted electricity. Using it on a live fire can create new pathways for current, posing a lethal electrocution risk to the user.",
    skillRequired: "electrical",
    difficulty: "medium",
  },
];

// CARPENTRY SKILL TEST - 10 Practical Questions
export const carpentryQuestions: PracticalQuestion[] = [
  {
    id: "carpentry-1",
    question: "A wooden door is sticking at the top corner. What is the most likely cause and first step?",
    scenario: "Customer reports a bedroom door that's hard to close during the humid season.",
    options: {
      a: "The door is too heavy for the hinges",
      b: "Humidity has caused the wood to swell; check hinge tightness first",
      c: "The house foundation is sinking",
      d: "The floor is uneven",
    },
    correctAnswer: "b",
    explanation: "Wood swells with humidity. Before planing the door, ensure hinges are tight and the door is properly aligned in the frame.",
    skillRequired: "carpentry",
    difficulty: "easy",
  },
  {
    id: "carpentry-2",
    question: "Which joint is strongest for connecting two pieces of wood at a 90-degree angle for a heavy-duty drawer?",
    scenario: "You are building custom kitchen drawers that will hold heavy pots and pans.",
    options: {
      a: "Butt joint with glue",
      b: "Dovetail joint",
      c: "Overlap joint",
      d: "Mitre joint with staples",
    },
    correctAnswer: "b",
    explanation: "Dovetail joints are famous for their tensile strength (resistance to being pulled apart) and are the standard for high-quality, heavy-duty cabinetry.",
    skillRequired: "carpentry",
    difficulty: "hard",
  },
  {
    id: "carpentry-3",
    question: "A customer wants to fix a wobbly wooden chair. What's the best approach?",
    scenario: "A dining chair has loose legs. The original glue has failed.",
    options: {
      a: "Drive long screws through the outside of the legs",
      b: "Disassemble the loose joints, clean off old glue, and re-glue with fresh wood glue and clamps",
      c: "Fill the gaps with sawdust and paint over it",
      d: "Use a lot of hot glue",
    },
    correctAnswer: "b",
    explanation: "Proper repair requires removing old, brittle glue, cleaning the wood fibers, and applying fresh glue under pressure (clamping) for a new permanent bond.",
    skillRequired: "carpentry",
    difficulty: "medium",
  },
  {
    id: "carpentry-4",
    question: "What is the primary purpose of a pilot hole?",
    scenario: "You are screwing a hinge into a piece of hardwood (teak).",
    options: {
      a: "To make the screw look straight",
      b: "To prevent the wood from splitting and make driving the screw easier",
      c: "To let the wood breathe",
      d: "To mark where the screw goes",
    },
    correctAnswer: "b",
    explanation: "Pilot holes remove a small amount of wood to create space for the screw's shank, preventing the internal pressure from splitting the wood grain.",
    skillRequired: "carpentry",
    difficulty: "easy",
  },
  {
    id: "carpentry-5",
    question: "How do you identify if wood rot is structural or just surface level?",
    scenario: "Checking an old window frame. Parts of the wood feel soft when pressed with a screwdriver.",
    options: {
      a: "If it looks dark, it's structural",
      b: "If a screwdriver easily penetrates more than 1/4 inch into the core, it's likely structural and needs replacement",
      c: "Wood rot is always structural",
      d: "Smell the wood for a 'musty' odor",
    },
    correctAnswer: "b",
    explanation: "The depth of penetration indicates how much of the wood fiber has been consumed by fungus. Deep penetration means the load-bearing capacity is compromised.",
    skillRequired: "carpentry",
    difficulty: "medium",
  },
  {
    id: "carpentry-6",
    question: "When installing baseboards on an uneven floor, how do you ensure a tight fit?",
    scenario: "The floor has a slight dip in the middle, leaving a gap under the baseboard.",
    options: {
      a: "Fill the gap with caulk",
      b: "Use a 'scribing' technique to match the baseboard profile to the floor's contour",
      c: "Push the baseboard down hard and nail it",
      d: "Add a second layer of baseboard",
    },
    correctAnswer: "b",
    explanation: "Scribing involves marking the floor's uneven profile onto the wood and cutting it to match, resulting in a perfect, gap-free fit.",
    skillRequired: "carpentry",
    difficulty: "hard",
  },
  {
    id: "carpentry-7",
    question: "Which sandpaper grit is best for final finishing before applying polish?",
    scenario: "You've sanded a table with 80 and 120 grit. What's next?",
    options: {
      a: "40 grit for better grip",
      b: "220 grit or higher for a smooth surface",
      c: "Steel wool only",
      d: "No more sanding needed",
    },
    correctAnswer: "b",
    explanation: "Higher grit numbers mean finer particles. 220 grit removes the scratches left by 120 grit, preparing the wood for a smooth finish.",
    skillRequired: "carpentry",
    difficulty: "easy",
  },
  {
    id: "carpentry-8",
    question: "How do you fix a stripped screw hole in a cabinet hinge?",
    scenario: "The screw just spins in the wood and won't tighten the hinge.",
    options: {
      a: "Use a larger screw",
      b: "Glue in wood splinters or a toothpick, let it dry, then re-drive the screw",
      c: "Move the hinge to a new location",
      d: "Tape the hinge on",
    },
    correctAnswer: "b",
    explanation: "Adding wood fibers (splinters/toothpicks) with glue provides 'meat' for the screw threads to bite into again without needing to move hardware.",
    skillRequired: "carpentry",
    difficulty: "medium",
  },
  {
    id: "carpentry-9",
    question: "What is 'grain direction' and why does it matter when planing wood?",
    scenario: "You are smoothing a rough plank using a hand plane.",
    options: {
      a: "It's just for looks",
      b: "Planing against the grain causes 'tear-out' (splintering); you must plane with the grain",
      c: "Grain direction changes every hour",
      d: "The plane works the same in both directions",
    },
    correctAnswer: "b",
    explanation: "Wood fibers grow in a specific direction. Cutting against them lifts and tears them, while cutting with them slices them cleanly.",
    skillRequired: "carpentry",
    difficulty: "medium",
  },
  {
    id: "carpentry-10",
    question: "What's the best way to ensure a shelf doesn't sag under heavy books?",
    scenario: "Installing bookshelves that are 4 feet wide.",
    options: {
      a: "Use thicker plywood only",
      b: "Use thicker material AND add a 'stiffener' (cleat) along the back or front edge",
      c: "Use more nails",
      d: "Tell the customer to use fewer books",
    },
    correctAnswer: "b",
    explanation: "Vertical stiffness is key. A horizontal cleat or edge banding significantly increases a shelf's resistance to bending over long spans.",
    skillRequired: "carpentry",
    difficulty: "medium",
  },
];

// PAINTING SKILL TEST - 10 Practical Questions
export const paintingQuestions: PracticalQuestion[] = [
  {
    id: "painting-1",
    question: "A wall has old peeling paint. What is your first step before applying new paint?",
    scenario: "You are hired to repaint a bedroom where the old paint is flaking off in several areas.",
    options: {
      a: "Paint over it with more coats",
      b: "Scrape off all loose paint, sand the edges smooth, and apply a primer",
      c: "Wash the wall with soap",
      d: "Glue the peeling parts back",
    },
    correctAnswer: "b",
    explanation: "New paint won't stick to loose, old paint. Proper prep requires removal of failing material and creating a smooth, primed base for adhesion.",
    skillRequired: "painting",
    difficulty: "easy",
  },
  {
    id: "painting-2",
    question: "Which type of paint is best for a bathroom with high humidity?",
    scenario: "Repainting a bathroom ceiling prone to steam.",
    options: {
      a: "Flat/Matte water-based paint",
      b: "Semi-gloss or Satin finish with mold/mildew resistance",
      c: "Standard whitewash",
      d: "Chalk paint",
    },
    correctAnswer: "b",
    explanation: "Glossier finishes are more moisture-resistant and easier to wipe clean. High humidity requires paint that doesn't absorb water easily.",
    skillRequired: "painting",
    difficulty: "medium",
  },
  {
    id: "painting-3",
    question: "What causes 'flashing' (uneven sheen) on a finished wall?",
    scenario: "After the wall dries, some spots look shinier than others under certain light.",
    options: {
      a: "Bad paint quality",
      b: "Uneven application, improper priming of patched areas, or painting in 'patches' instead of wet-to-dry",
      c: "The wall is haunted",
      d: "Too much sunlight",
    },
    correctAnswer: "b",
    explanation: "Flashing happens when porous areas (like patches) absorb paint differently or when a dry edge is overlapped with wet paint.",
    skillRequired: "painting",
    difficulty: "hard",
  },
  {
    id: "painting-4",
    question: "How do you properly clean a brush used for oil-based paint?",
    scenario: "You just finished painting a wooden door with oil enamel.",
    options: {
      a: "Use warm soapy water",
      b: "Use mineral spirits or turpentine, then wash with soap and water",
      c: "Let it dry and peel the paint off",
      d: "Throw it away",
    },
    correctAnswer: "b",
    explanation: "Oil-based paints don't dissolve in water. Chemical solvents are needed to break down the resin before a final soap wash.",
    skillRequired: "painting",
    difficulty: "medium",
  },
  {
    id: "painting-5",
    question: "What is the purpose of 'cutting in'?",
    scenario: "You are starting to paint a large room.",
    options: {
      a: "Cutting the paint with water to make it thinner",
      b: "Painting the edges (corners, ceiling line) with a brush before using a roller on the main area",
      c: "Cutting the cost of the project",
      d: "Mixing two different colors together",
    },
    correctAnswer: "b",
    explanation: "Cutting in ensures clean lines around obstacles and corners where a roller cannot reach or produces a messy finish.",
    skillRequired: "painting",
    difficulty: "easy",
  },
  {
    id: "painting-6",
    question: "Why would paint start bubbling or blistering shortly after application?",
    scenario: "Paint on an exterior wall is forming small bubbles as it dries.",
    options: {
      a: "The paint is high quality",
      b: "Moisture trapped under the paint or painting on a surface that is too hot (direct sun)",
      c: "Using too much paint",
      d: "The wall was too smooth",
    },
    correctAnswer: "b",
    explanation: "Bubbles occur when expanding moisture or gases try to escape from behind the sealing paint film, often due to heat or dampness.",
    skillRequired: "painting",
    difficulty: "medium",
  },
  {
    id: "painting-7",
    question: "How do you transition from a dark wall color to a light one effectively?",
    scenario: "Customer wants to change a navy blue wall to off-white.",
    options: {
      a: "Apply 5 coats of white paint",
      b: "Apply a high-hide grey or white primer first, then 2 coats of the light color",
      c: "Scrape the blue paint off",
      d: "Wait for the blue to fade in the sun",
    },
    correctAnswer: "b",
    explanation: "Primer provides high opacity to block the underlying dark pigment, reducing the number of expensive topcoat layers needed.",
    skillRequired: "painting",
    difficulty: "medium",
  },
  {
    id: "painting-8",
    question: "What is the correct way to load a paint roller?",
    scenario: "You are about to start rolling a large living room wall.",
    options: {
      a: "Submerge the whole roller in the bucket",
      b: "Roll it into the tray well, then roll it back and forth on the ramp to distribute paint evenly",
      c: "Dip only one side and start rolling",
      d: "Pour paint directly onto the wall",
    },
    correctAnswer: "b",
    explanation: "The tray ramp is designed to spin the roller and distribute paint evenly into the fibers, preventing drips and uneven coverage.",
    skillRequired: "painting",
    difficulty: "easy",
  },
  {
    id: "painting-9",
    question: "When should you remove painter's tape for the cleanest line?",
    scenario: "You've finished the second coat of trim paint.",
    options: {
      a: "Wait 2 days until it's rock hard",
      b: "While the paint is still slightly tacky/wet OR score it with a blade if it's completely dry",
      c: "Remove it before you start painting",
      d: "Leave it on; it protects the edges forever",
    },
    correctAnswer: "b",
    explanation: "Removing tape when paint is wet prevents the drying paint film from sticking to the tape and tearing away from the wall.",
    skillRequired: "painting",
    difficulty: "medium",
  },
  {
    id: "painting-10",
    question: "How do you fix a large hole in drywall before painting?",
    scenario: "There's a 3-inch hole where a doorknob hit the wall.",
    options: {
      a: "Stuff it with newspaper and paint over",
      b: "Use a mesh patch or a 'California patch' with joint compound, sand, and prime",
      c: "Cover it with a picture frame",
      d: "Fill the whole thing with toothpaste",
    },
    correctAnswer: "b",
    explanation: "Drywall repair requires structural bridging (mesh/patch) and multiple thin layers of compound to disappear into the surrounding wall.",
    skillRequired: "painting",
    difficulty: "medium",
  },
];

// AC REPAIR SKILL TEST - 10 Practical Questions
export const acRepairQuestions: PracticalQuestion[] = [
  {
    id: "ac-1",
    question: "An AC is running but not cooling. What's the first diagnostic check?",
    scenario: "Customer says the indoor unit is blowing air, but it's not cold.",
    options: {
      a: "Replace the compressor immediately",
      b: "Check if the outdoor unit compressor and fan are running; check for dirty air filters",
      c: "Add more gas (refrigerant) blindly",
      d: "Tell the customer to buy a new AC",
    },
    correctAnswer: "b",
    explanation: "Always start with the basics. Dirty filters block airflow, and if the outdoor unit isn't starting, the cooling cycle won't begin.",
    skillRequired: "ac-repair",
    difficulty: "easy",
  },
  {
    id: "ac-2",
    question: "What does ice formation on the indoor evaporator coils indicate?",
    scenario: "The indoor unit is spitting ice cubes or has a thick layer of frost on the coils.",
    options: {
      a: "The AC is working extra well",
      b: "Restricted airflow (dirty filters/fan) or low refrigerant levels",
      c: "The temperature setting is too high",
      d: "It's a feature of modern ACs",
    },
    correctAnswer: "b",
    explanation: "Ice forms when the coil temperature drops below freezing. This happens if there's not enough air passing over it to transfer heat or if low pressure causes the gas to be too cold.",
    skillRequired: "ac-repair",
    difficulty: "medium",
  },
  {
    id: "ac-3",
    question: "How do you properly check for a refrigerant leak?",
    scenario: "You suspect the system is low on R32 gas.",
    options: {
      a: "Look for oil stains on joints and use a soap bubble test or electronic leak detector",
      b: "Listen for a whistling sound",
      c: "Smell the air for a 'fruity' scent",
      d: "Just keep refilling until it stops working",
    },
    correctAnswer: "a",
    explanation: "Refrigerant contains oil; leaks usually leave a residue. Soap bubbles are a reliable, low-cost way to pinpoint high-pressure gas leaks at joints.",
    skillRequired: "ac-repair",
    difficulty: "hard",
  },
  {
    id: "ac-4",
    question: "The AC indoor unit is leaking water inside the room. What is the most likely fix?",
    scenario: "Water is dripping from the bottom of the split AC indoor unit.",
    options: {
      a: "The AC is melting",
      b: "The drain pipe is clogged with dust/slime or the drain tray is tilted incorrectly",
      c: "Too much humidity in the room",
      d: "The fan speed is too low",
    },
    correctAnswer: "b",
    explanation: "Condensation from the coils should flow out through a pipe. If it's blocked, the tray overflows into the room.",
    skillRequired: "ac-repair",
    difficulty: "easy",
  },
  {
    id: "ac-5",
    question: "What is the purpose of a start capacitor in an AC?",
    scenario: "The outdoor fan spins, but the compressor makes a 'humming' sound and doesn't start.",
    options: {
      a: "To keep the AC cool",
      b: "To provide the initial electrical 'kick' needed to get the compressor motor spinning",
      c: "To save electricity",
      d: "To control the remote signal",
    },
    correctAnswer: "b",
    explanation: "Compressors need high torque to start. A capacitor stores energy to provide this momentary surge. A failed capacitor is a very common 'humming' issue.",
    skillRequired: "ac-repair",
    difficulty: "medium",
  },
  {
    id: "ac-6",
    question: "Why is 'vacuuming' the lines important during a new installation?",
    scenario: "You are connecting a new split unit and have just finished flared connections.",
    options: {
      a: "To remove dust from the room",
      b: "To remove moisture and air from the refrigerant lines to prevent compressor damage and ensure efficiency",
      c: "To test the strength of the pipes",
      d: "It's not important, just open the valves",
    },
    correctAnswer: "b",
    explanation: "Moisture in the system combines with oil to form acid, which eats the compressor motor. Air is non-condensable and raises head pressure, reducing cooling.",
    skillRequired: "ac-repair",
    difficulty: "hard",
  },
  {
    id: "ac-7",
    question: "An AC compressor shuts off after 5 minutes of cooling (Short Cycling). What do you check?",
    scenario: "AC starts fine but the outdoor unit stops frequently while the indoor keeps blowing warm air.",
    options: {
      a: "Remote batteries are low",
      b: "Check for dirty condenser coils (outdoor), faulty run capacitor, or compressor overheating (high amp draw)",
      c: "The room is already too cold",
      d: "Increase the fan speed",
    },
    correctAnswer: "b",
    explanation: "If the outdoor unit can't reject heat (dirty coils), it overheats and the 'internal protector' shuts it off to prevent a burnout.",
    skillRequired: "ac-repair",
    difficulty: "medium",
  },
  {
    id: "ac-8",
    question: "What is the difference between Inverter and Non-Inverter ACs regarding repair?",
    scenario: "You are called to fix an AC that doesn't respond to the remote.",
    options: {
      a: "Inverters use less gas",
      b: "Inverters have complex PC boards in both indoor and outdoor units that communicate; Non-inverters are simpler relay-based systems",
      c: "Inverters cannot be repaired, only replaced",
      d: "There is no difference in the wiring",
    },
    correctAnswer: "b",
    explanation: "Inverter technology relies heavily on electronics (PCB) to vary motor speed. Debugging usually requires checking LED error codes on the boards.",
    skillRequired: "ac-repair",
    difficulty: "medium",
  },
  {
    id: "ac-9",
    question: "How do you identify a 'grounded' compressor?",
    scenario: "The main MCB trips immediately as soon as you turn on the AC.",
    options: {
      a: "The wire is too long",
      b: "Test for continuity between the compressor terminals and the copper body using a multimeter",
      c: "Check if the remote is working",
      d: "The gas is too high",
    },
    correctAnswer: "b",
    explanation: "A grounded compressor means the internal motor winding insulation has failed and is touching the metal shell, causing a direct short circuit.",
    skillRequired: "ac-repair",
    difficulty: "hard",
  },
  {
    id: "ac-10",
    question: "What is the correct way to clean the outdoor condenser unit?",
    scenario: "The outdoor unit is covered in thick dust and mud.",
    options: {
      a: "Use a high-pressure jet directly at the fan motor",
      b: "Gently spray water through the fins in the opposite direction of airflow; avoid getting the electrical box wet",
      c: "Brush it with a dry broom",
      d: "Spray it with WD-40",
    },
    correctAnswer: "b",
    explanation: "Water should flow through the fins to clear blockages. High pressure can bend the thin aluminum fins, ruining airflow forever.",
    skillRequired: "ac-repair",
    difficulty: "easy",
  },
];

// APPLIANCE REPAIR SKILL TEST - 10 Practical Questions
export const applianceRepairQuestions: PracticalQuestion[] = [
  {
    id: "app-1",
    question: "A washing machine is vibrating violently during the spin cycle. What is likely wrong?",
    scenario: "The machine walks across the floor and makes a loud banging noise when it reaches high speed.",
    options: {
      a: "The motor is too strong",
      b: "Unbalanced load, unlevel feet, or worn-out suspension springs/shock absorbers",
      c: "The timer is wrong",
      d: "Use more detergent",
    },
    correctAnswer: "b",
    explanation: "Vibration is a physical balance issue. Leveling the machine is step one; checking the dampening system (shocks) is step two.",
    skillRequired: "appliance-repair",
    difficulty: "easy",
  },
  {
    id: "app-2",
    question: "A refrigerator is completely dead - no lights, no sound. What's your first move?",
    scenario: "Customer says their fridge stopped working overnight.",
    options: {
      a: "Gas is finished",
      b: "Check the power outlet, fuse, and the main power cord for continuity",
      c: "Replace the thermostat",
      d: "Recommend a new fridge",
    },
    correctAnswer: "b",
    explanation: "No lights usually means a power supply issue, not a cooling issue. Start at the plug.",
    skillRequired: "appliance-repair",
    difficulty: "easy",
  },
  {
    id: "app-3",
    question: "A microwave runs and turns, but the food is still cold. What is the most likely culprit?",
    scenario: "The light comes on and the tray spins for 2 minutes, but the glass of water inside is room temperature.",
    options: {
      a: "The door isn't closed right",
      b: "Failed High Voltage Magnetron, Diode, or Capacitor",
      c: "The user is using the wrong plate",
      d: "The fuse is blown",
    },
    correctAnswer: "b",
    explanation: "If the machine powers up and spins, the 'low voltage' side is fine. The 'high voltage' components that generate the actual microwaves have likely failed.",
    skillRequired: "appliance-repair",
    difficulty: "hard",
  },
  {
    id: "app-4",
    question: "Water is not draining from a front-load washing machine. What do you check first?",
    scenario: "The cycle stops with water still in the drum.",
    options: {
      a: "The door lock is broken",
      b: "Check and clean the drain pump filter (usually at the bottom front)",
      c: "The inlet valve is stuck open",
      d: "The drum is too heavy",
    },
    correctAnswer: "b",
    explanation: "Coins, hairpins, and lint frequently clog the pump filter, preventing the pump from pushing water out.",
    skillRequired: "appliance-repair",
    difficulty: "easy",
  },
  {
    id: "app-5",
    question: "A refrigerator freezer is cold, but the fresh food compartment (bottom) is warm. What's the issue?",
    scenario: "Ice cream is frozen, but the milk below is spoiled.",
    options: {
      a: "Low gas",
      b: "Failed defrost heater, timer, or fridge-to-freezer air damper/fan",
      c: "Door seal is slightly loose",
      d: "Thermostat is set too high",
    },
    correctAnswer: "b",
    explanation: "Most fridges use one evaporator in the freezer. If the defrost fails, ice blocks the air passages to the fridge. Or the fan that moves air is dead.",
    skillRequired: "appliance-repair",
    difficulty: "medium",
  },
  {
    id: "app-6",
    question: "Which component in a microwave can hold a lethal electrical charge even after it's unplugged?",
    scenario: "You have unplugged a microwave to check the internal wiring.",
    options: {
      a: "The light bulb",
      b: "The High Voltage Capacitor",
      c: "The turntable motor",
      d: "The control panel",
    },
    correctAnswer: "b",
    explanation: "The HV capacitor stores several thousand volts. It must be safely discharged with an insulated tool before touching ANY internals.",
    skillRequired: "appliance-repair",
    difficulty: "hard",
  },
  {
    id: "app-7",
    question: "An electric iron doesn't heat up, but the power light is ON. What is the fix?",
    scenario: "The indicator bulb glows when plugged in, but the soleplate stays cold.",
    options: {
      a: "The cord is broken",
      b: "The internal heating element is open (burnt out) or the thermostat contacts are badly pitted",
      c: "Use more water in the spray",
      d: "Clean the plate with salt",
    },
    correctAnswer: "b",
    explanation: "Light on means power reaches the device. No heat means the actual resistance element is broken or the switch (thermostat) isn't completing the circuit.",
    skillRequired: "appliance-repair",
    difficulty: "medium",
  },
  {
    id: "app-8",
    question: "What does 'E1' or similar error codes on an Induction Cooktop usually mean?",
    scenario: "The cooktop beeps and shows 'E1' when the customer puts a pan on it.",
    options: {
      a: "It's a system crash",
      b: "No pan detected or incompatible pan (not ferromagnetic/not iron-based)",
      c: "The electricity is low",
      d: "The glass is too hot",
    },
    correctAnswer: "b",
    explanation: "Induction requires magnetic materials to work. Aluminum or glass pans won't trigger the electromagnetic field.",
    skillRequired: "appliance-repair",
    difficulty: "medium",
  },
  {
    id: "app-9",
    question: "How do you test a refrigerator's door seal (gasket)?",
    scenario: "Customer reports high bills and condensation on the outside of the fridge door.",
    options: {
      a: "Use a candle flame to see if it flickers",
      b: "The 'Dollar Bill Test': close the door on a bill; if it pulls out with no resistance, the seal is bad",
      c: "Pour water on the seal to see if it leaks",
      d: "Visual inspection only",
    },
    correctAnswer: "b",
    explanation: "A good seal should provide firm resistance when you try to pull paper through it. No resistance means cold air is escaping.",
    skillRequired: "appliance-repair",
    difficulty: "easy",
  },
  {
    id: "app-10",
    question: "What is 'Scale' in a geyser (water heater) and how does it affect it?",
    scenario: "Water heater is taking twice as long as before to heat the tank.",
    options: {
      a: "It's the brand of the heater",
      b: "Mineral deposits from hard water coating the element, insulating it and causing it to run longer and eventually burn out",
      c: "It's rust on the outside",
      d: "The tank is getting bigger",
    },
    correctAnswer: "b",
    explanation: "Hard water minerals form a crust on heating elements. This slows heat transfer to the water, wasting energy and killing the element.",
    skillRequired: "appliance-repair",
    difficulty: "medium",
  },
];

// CLEANING SKILL TEST - 10 Practical Questions
export const cleaningQuestions: PracticalQuestion[] = [
  {
    id: "clean-1",
    question: "What is the safest way to clean a delicate silk or velvet fabric sofa?",
    scenario: "Customer has an expensive imported sofa with a stain.",
    options: {
      a: "Use a high-pressure steam cleaner",
      b: "Dry foam cleaning or specialized mild solvent, following the 'S' cleaning code",
      c: "Scrub with bleach and water",
      d: "Use a regular vacuum and a wet cloth",
    },
    correctAnswer: "b",
    explanation: "Water can ruin the texture of silk or velvet. Dry cleaning methods are essential for luxury fabrics.",
    skillRequired: "cleaning",
    difficulty: "medium",
  },
  {
    id: "clean-2",
    question: "Which chemical should NEVER be mixed with Bleach?",
    scenario: "You are preparing cleaning solutions for a bathroom deep-clean.",
    options: {
      a: "Soap",
      b: "Ammonia or Vinegar (acidic cleaners); it creates toxic chlorine gas",
      c: "Water",
      d: "Baking soda",
    },
    correctAnswer: "b",
    explanation: "Mixing bleach with ammonia or acids creates deadly gases. This is a critical safety rule for professional cleaners.",
    skillRequired: "cleaning",
    difficulty: "hard",
  },
  {
    id: "clean-3",
    question: "How do you remove a red wine stain from a light-colored carpet?",
    scenario: "Fresh spill during a party, customer calls for urgent help.",
    options: {
      a: "Rub it hard with a wet towel",
      b: "Blot (don't rub), apply salt or club soda to absorb, then use specialized enzyme cleaner",
      c: "Wait for it to dry and then vacuum",
      d: "Apply more red wine to even it out",
    },
    correctAnswer: "b",
    explanation: "Rubbing pushes the pigment deeper into fibers. Blotting keeps it on the surface for extraction.",
    skillRequired: "cleaning",
    difficulty: "easy",
  },
  {
    id: "clean-4",
    question: "What is the 'top-to-bottom' rule in professional cleaning?",
    scenario: "You are starting a deep-clean of a 3-bedroom apartment.",
    options: {
      a: "Clean the basement first then the roof",
      b: "Always clean from high areas (fans, tops of cupboards) to low areas (floors) so dust doesn't fall on clean surfaces",
      c: "Start with the most expensive items",
      d: "Clean high-traffic areas first",
    },
    correctAnswer: "b",
    explanation: "Cleaning low areas first is a waste of time because tasks done later in higher spots will drop dust back down onto them.",
    skillRequired: "cleaning",
    difficulty: "easy",
  },
  {
    id: "clean-5",
    question: "How do you clean a TV or Monitor screen safely?",
    scenario: "Customer wants their expensive OLED TV screen cleaned.",
    options: {
      a: "Spray glass cleaner directly on the screen",
      b: "Use a dry microfiber cloth or a cloth slightly dampened with distilled water/dedicated screen cleaner",
      c: "Wipe with a paper towel and soap",
      d: "Use a wet sponge",
    },
    correctAnswer: "b",
    explanation: "Modern screens have delicate coatings and electronics. Sprays can leak into the bezel and fry the panel; abrasive paper towels scratch the coating.",
    skillRequired: "cleaning",
    difficulty: "medium",
  },
  {
    id: "clean-6",
    question: "What is an 'Enzymatic Cleaner' best used for?",
    scenario: "A customer's pet has had an accident on the carpet.",
    options: {
      a: "Cleaning windows",
      b: "Removing biological stains (urine, blood, sweat) by breaking down the organic molecules and odors",
      c: "Polishing silver",
      d: "Removing grease from a stove",
    },
    correctAnswer: "b",
    explanation: "Enzymes 'eat' the organic matter that causes odors and stains, ensuring the smell doesn't return or attract the pet again.",
    skillRequired: "cleaning",
    difficulty: "medium",
  },
  {
    id: "clean-7",
    question: "How do you remove hard water lime-scale from a shower head?",
    scenario: "The shower head is blocked by white mineral crust.",
    options: {
      a: "Chip it off with a hammer",
      b: "Soak it in a bag of white vinegar or a descaling agent for a few hours",
      c: "Paint over it",
      d: "Increase the water pressure",
    },
    correctAnswer: "b",
    explanation: "Vinegar is a mild acid that dissolves the alkaline calcium deposits without damaging the fixture.",
    skillRequired: "cleaning",
    difficulty: "easy",
  },
  {
    id: "clean-8",
    question: "What's the correct way to vacuum or clean under a heavy bed?",
    scenario: "Performing a deep-clean service.",
    options: {
      a: "Skip it, nobody looks there",
      b: "Use a flat-head vacuum attachment or move the bed safely (with help) to ensure no 'dust bunnies' remain",
      c: "Blow air from one side to the other",
      d: "Tell the customer to buy a higher bed",
    },
    correctAnswer: "b",
    explanation: "Professional cleaning means cleaning where customers usually don't. These hidden areas are traps for allergens and pests.",
    skillRequired: "cleaning",
    difficulty: "easy",
  },
  {
    id: "clean-9",
    question: "How do you handle a grease fire in a kitchen you are cleaning?",
    scenario: "A shallow pan of oil has caught fire on the stove.",
    options: {
      a: "Throw water on it immediately",
      b: "Turn off the heat and slide a metal lid over the pan to starve it of oxygen; never use water",
      c: "Blow on it to put it out",
      d: "Pick up the pan and run outside",
    },
    correctAnswer: "b",
    explanation: "Water on a grease fire causes a massive fireball (explosion). Smothering it is the only safe way to stop it.",
    skillRequired: "cleaning",
    difficulty: "hard",
  },
  {
    id: "clean-10",
    question: "What is the purpose of 'PH-Neutral' cleaner for stone floors?",
    scenario: "Cleaning a polished marble or granite lobby.",
    options: {
      a: "To make it smell like lemons",
      b: "To prevent 'etching' (dulling/eating) the stone surface, which happens with acidic cleaners",
      c: "It makes the floor dry faster",
      d: "It's the cheapest type of cleaner",
    },
    correctAnswer: "b",
    explanation: "Natural stones like marble are sensitive to acids (vinegar/lemon). PH-neutral cleaners protect the expensive polish from being destroyed.",
    skillRequired: "cleaning",
    difficulty: "medium",
  },
];

// Export combined tests
export const skillTests: Record<string, SkillTest> = {
  plumbing: {
    testId: "test-plumbing-001",
    skillId: "plumbing",
    skillName: "Plumbing",
    totalQuestions: 10,
    passingScore: 70,
    timeLimit: 30,
    questions: plumbingQuestions,
  },
  electrical: {
    testId: "test-electrical-001",
    skillId: "electrical",
    skillName: "Electrical Work",
    totalQuestions: 10,
    passingScore: 70,
    timeLimit: 30,
    questions: electricalQuestions,
  },
  carpentry: {
    testId: "test-carpentry-001",
    skillId: "carpentry",
    skillName: "Carpentry",
    totalQuestions: 10,
    passingScore: 70,
    timeLimit: 30,
    questions: carpentryQuestions,
  },
  painting: {
    testId: "test-painting-001",
    skillId: "painting",
    skillName: "Painting & Decoration",
    totalQuestions: 10,
    passingScore: 70,
    timeLimit: 30,
    questions: paintingQuestions,
  },
  "ac-repair": {
    testId: "test-ac-001",
    skillId: "ac-repair",
    skillName: "AC & Cooling Systems",
    totalQuestions: 10,
    passingScore: 70,
    timeLimit: 30,
    questions: acRepairQuestions,
  },
  "appliance-repair": {
    testId: "test-appliance-001",
    skillId: "appliance-repair",
    skillName: "Appliance Repair",
    totalQuestions: 10,
    passingScore: 70,
    timeLimit: 30,
    questions: applianceRepairQuestions,
  },
  cleaning: {
    testId: "test-cleaning-001",
    skillId: "cleaning",
    skillName: "Professional Cleaning",
    totalQuestions: 10,
    passingScore: 70,
    timeLimit: 30,
    questions: cleaningQuestions,
  },
};

export const skillsDatabase = [
  {
    id: "plumbing",
    name: "Plumbing",
    description: "Water supply, drainage, and pipe fitting expertise",
    icon: "🔧",
    category: "skilled-trades",
    testId: "test-plumbing-001",
  },
  {
    id: "electrical",
    name: "Electrical Work",
    description: "Safe electrical installation, repair, and troubleshooting",
    icon: "⚡",
    category: "skilled-trades",
    testId: "test-electrical-001",
  },
  {
    id: "carpentry",
    name: "Carpentry",
    description: "Wood work, furniture, and structural carpentry",
    icon: "🪵",
    category: "skilled-trades",
    testId: "test-carpentry-001",
  },
  {
    id: "painting",
    name: "Painting & Decoration",
    description: "Interior and exterior painting and finishing",
    icon: "🎨",
    category: "skilled-trades",
    testId: "test-painting-001",
  },
  {
    id: "ac-repair",
    name: "AC & Cooling Systems",
    description: "Air conditioning installation, maintenance, and repair",
    icon: "❄️",
    category: "specialized-trades",
    testId: "test-ac-001",
  },
  {
    id: "appliance-repair",
    name: "Appliance Repair",
    description: "Refrigerator, washing machine, and appliance repairs",
    icon: "🧊",
    category: "specialized-trades",
    testId: "test-appliance-001",
  },
  {
    id: "cleaning",
    name: "Professional Cleaning",
    description: "Home and office cleaning services",
    icon: "🧹",
    category: "services",
    testId: "test-cleaning-001",
  },
];
